### ISSUE TITLE
plz help!

### ISSUE THREAD

**Issue by raedaf** [helgi-leifsson/Wumpus#1]
I run this code but I have error on 
Rule r1 = new Rule( f1, f2, null, null, null, Connector.Conjunction, Type.Facts );
        Rule r2 = new Rule( f3, f4, null, null, null, Connector.Conjunction, Type.Facts );
        Rule r3 = new Rule( f5, f6, null, null, null, Connector.Conjunction, Type.Facts );
        Rule r4 = new Rule( f7, f8, null, null, null, Connector.Conjunction, Type.Facts );

Type.Facts doesn't identified 
any advice regarding this plz

**Comment by helgi-leifsson** [comment]
The name of the enum Type must have been conflicting with some other entity named Type. Moved the enum to its own file and changed the name to RuleFactType and the project now runs. Thanks.

**Comment by raedaf** [comment]
thank you very much
I have another question how I  can change gold, pit and wumpus position and create its position randomly
